<?php

use Illuminate\Database\Seeder;

class DeweySeeder extends Seeder 

{

	public function run() 
	{
		DB::table("deweys")->insert(["number" => 1, "parent" => null, "category" => "Philosophy & Psychology"]);
		DB::table("deweys")->insert(["number" => 2, "parent" => null, "category" => "Religion"]);
		DB::table("deweys")->insert(["number" => 3, "parent" => null, "category" => "Social Sciences"]);
		DB::table("deweys")->insert(["number" => 4, "parent" => null, "category" => "Language"]);
		DB::table("deweys")->insert(["number" => 5, "parent" => null, "category" => "Science"]);
		DB::table("deweys")->insert(["number" => 6, "parent" => null, "category" => "Techology"]);
		DB::table("deweys")->insert(["number" => 7, "parent" => null, "category" => "Arts & Recreation"]);
		DB::table("deweys")->insert(["number" => 8, "parent" => null, "category" => "Literature"]);
		DB::table("deweys")->insert(["number" => 9, "parent" => null, "category" => "History & Geography"]);
		DB::table("deweys")->insert(["number" => 0, "parent" => null, "category" => "Computer science, information & general works"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 0, "category" => "Knowledge"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 0, "category" => "The book (writing, libraries, and book-related topics)"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 0, "category" => "Systems"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 0, "category" => "Data processing & computer science"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 0, "category" => "Computer programming, programs & data"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 0, "category" => "Special computer methods"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 1, "category" => "Bibliographies"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 1, "category" => "Bibliographies of individuals"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 1, "category" => "Bibliographies of anonymous & pseudonymous works"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 1, "category" => "Bibliographies of works from specific places"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 1, "category" => "Bibliographies of works on specific subjects"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 1, "category" => "General subject catalogs"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 1, "category" => "Catalogs arranged by author, date, etc."]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 1, "category" => "Dictionary catalogs"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 2, "category" => "Library relationships (with archives, information centers, etc.)"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 2, "category" => "Administration of physical plant"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 2, "category" => "Personnel management"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 2, "category" => "Library operations"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 2, "category" => "Libraries for specific subjects"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 2, "category" => "General libraries"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 2, "category" => "Reading & use of other information media"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 3, "category" => "Encyclopedias in American English"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 3, "category" => "Encyclopedias in English"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 3, "category" => "Encyclopedias in other Germanic languages"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 3, "category" => "Encyclopedias in French, Occitan, and Catalan"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 3, "category" => "Encyclopedias in Italian, Romanian, and related languages"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 3, "category" => "Encyclopedias in Spanish & Portuguese"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 3, "category" => "Encyclopedias in Slavic languages"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 3, "category" => "Encyclopedias in Scandinavian languages"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 3, "category" => "Encyclopedias in other languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 5, "category" => "Serials in American English"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 5, "category" => "Serials in English"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 5, "category" => "Serials in other Germanic languages"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 5, "category" => "Serials in French, Occitan, and Catalan"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 5, "category" => "Serials in Italian, Romanian, and related languages"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 5, "category" => "Serials in Spanish & Portuguese"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 5, "category" => "Serials in Slavic languages"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 5, "category" => "Serials in Scandinavian languages"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 5, "category" => "Serials in other languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 6, "category" => "Organizations in North America"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 6, "category" => "Organizations in British Isles; in England"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 6, "category" => "Organizations in central Europe; in Germany"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 6, "category" => "Organizations in France & Monaco"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 6, "category" => "Organizations in Italy & adjacent islands"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 6, "category" => "Organizations in Iberian peninsula & adjacent islands"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 6, "category" => "Organizations in eastern Europe; in Russia"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 6, "category" => "Organizations in other geographic areas"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 6, "category" => "Museum science"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 7, "category" => "Newspapers in North America"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 7, "category" => "Newspapers in British Isles; in England"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 7, "category" => "Newspapers in central Europe; in Germany"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 7, "category" => "Newspapers in France & Monaco"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 7, "category" => "Newspapers in Italy & adjacent islands"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 7, "category" => "Newspapers in Iberian peninsula & adjacent islands"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 7, "category" => "Newspapers in eastern Europe; in Russia"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 7, "category" => "Newspapers in Scandinavia"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 7, "category" => "Newspapers in other geographic areas"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 8, "category" => "Collections in American English"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 8, "category" => "Collections in English"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 8, "category" => "Collections in other Germanic languages"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 8, "category" => "Collections in French, Occitan, Catalan"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 8, "category" => "Collections in Italian, Romanian, & related languages"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 8, "category" => "Collections in Spanish & Portuguese"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 8, "category" => "Collections in Slavic languages"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 8, "category" => "Collections in Scandinavian languages"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 8, "category" => "Collections in other languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 9, "category" => "Manuscripts"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 9, "category" => "Block books"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 9, "category" => "Incunabula"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 9, "category" => "Printed books"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 9, "category" => "Books notable for bindings"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 9, "category" => "Books notable for illustrations"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 9, "category" => "Books notable for ownership or origin"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 9, "category" => "Prohibited works, forgeries, and hoaxes"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 9, "category" => "Books notable for format"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 10, "category" => "Theory of philosophy"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 10, "category" => "Miscellany"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 10, "category" => "Dictionaries & encyclopedias"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 10, "category" => "Serial publications"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 10, "category" => "Organizations & management"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 10, "category" => "Education, research, related topics of philosophy"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 10, "category" => "Groups of people"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 10, "category" => "History & collected biography"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 11, "category" => "Ontology"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 11, "category" => "No longer used—formerly Methodology"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 11, "category" => "Cosmology (Philosophy of nature)"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 11, "category" => "Space"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 11, "category" => "Time"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 11, "category" => "Change"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 11, "category" => "Structure"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 11, "category" => "Force and energy"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 11, "category" => "Number and quantity"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 12, "category" => "Epistemology (Theory of knowledge)"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 12, "category" => "Causation"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 12, "category" => "Determinism and indeterminism"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 12, "category" => "Teleology"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 12, "category" => "No longer used—formerly Infinity"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 12, "category" => "The self"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 12, "category" => "The unconscious & the subconscious"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 12, "category" => "Humankind"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 12, "category" => "Origin & destiny of individual souls"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 13, "category" => "Parapsychological and occult methods for achieving well-being, happiness, success"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 13, "category" => "No longer used—formerly Mental derangements"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 13, "category" => "Specific topics in parapsychology & occultism"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 13, "category" => "No longer used—formerly Mesmerism & Clairvoyance"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 13, "category" => "Dreams & mysteries"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 13, "category" => "No longer used—formerly Mental characteristics"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 13, "category" => "Divinatory graphology"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 13, "category" => "Physiognomy"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 13, "category" => "Phrenology"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 14, "category" => "Idealism & related systems & doctrines"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 14, "category" => "Critical philosophy"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 14, "category" => "Bergsonism & intuitionism"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 14, "category" => "Humanism & related systems & doctrines"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 14, "category" => "Sensationalism"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 14, "category" => "Naturalism & related systems & doctrines"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 14, "category" => "Pantheism & related systems & doctrines"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 14, "category" => "Dogmatism, eclecticism, liberalism, syncretism, & traditionalism"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 14, "category" => "Other philosophical systems & doctrines"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 15, "category" => "No longer used—formerly Intellect"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 15, "category" => "Sensory perception, movement, emotions, & physiological drives"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 15, "category" => "Conscious mental processes & intelligence"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 15, "category" => "Subconscious & altered states & processes"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 15, "category" => "Differential & developmental psychology"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 15, "category" => "Comparative psychology"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 15, "category" => "No longer used—formerly Emotions"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 15, "category" => "Applied psychology"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 15, "category" => "No longer used—formerly Will"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 16, "category" => "Induction"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 16, "category" => "Deduction"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 16, "category" => "Fallacies & sources of error"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 16, "category" => "Syllogisms"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 16, "category" => "Hypotheses"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 16, "category" => "Argument & persuasion"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 16, "category" => "Analogy"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 17, "category" => "Ethical systems"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 17, "category" => "Political ethics"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 17, "category" => "Ethics of family relationships"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 17, "category" => "Occupational ethics"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 17, "category" => "Ethics of recreation, leisure, public performances, communication"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 17, "category" => "Ethics of sex & reproduction"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 17, "category" => "Ethics of social relations"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 17, "category" => "Ethics of consumption"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 17, "category" => "Other ethical norms"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 18, "category" => "Eastern philosophy"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 18, "category" => "Pre-Socratic Greek philosophies"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 18, "category" => "Sophistic, Socratic, related Greek philosophies"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 18, "category" => "Platonic philosophy"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 18, "category" => "Aristotelian philosophy"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 18, "category" => "Skeptic & Neoplatonic philosophies"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 18, "category" => "Epicurean philosophy"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 18, "category" => "Stoic philosophy"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 18, "category" => "Medieval Western philosophy"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 19, "category" => "Philosophy of the United States and Canada"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 19, "category" => "Philosophy of the British Isles"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 19, "category" => "Philosophy of Germany and Austria"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 19, "category" => "Philosophy of France"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 19, "category" => "Philosophy of Italy"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 19, "category" => "Philosophy of Spain and Portugal"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 19, "category" => "Philosophy of Russia"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 19, "category" => "Philosophy of Scandinavia & Finland"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 19, "category" => "Philosophy in other geographic areas"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 20, "category" => "Religious mythology, general classes of religion, interreligious relations and attitudes, social theology"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 20, "category" => "Doctrines"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 20, "category" => "Public worship and other practices"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 20, "category" => "Religious experience, life, practice"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 20, "category" => "Religious ethics"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 20, "category" => "Leaders and organization"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 20, "category" => "Missions and religious education"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 20, "category" => "Sources"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 20, "category" => "Sects and reform movements"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 21, "category" => "Concepts of God"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 21, "category" => "Existence, ways of knowing God, attributes of God"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 21, "category" => "Creation"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 21, "category" => "Theodicy"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 21, "category" => "Science & religion"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 21, "category" => "No longer used—formerly Evil"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 21, "category" => "No longer used—formerly Prayer"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 21, "category" => "Humankind"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 21, "category" => "No longer used—formerly Analogies"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 22, "category" => "Old Testament (Tanakh)"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 22, "category" => "Historical books of Old Testament"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 22, "category" => "Poetic books of Old Testament"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 22, "category" => "Prophetic books of Old Testament"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 22, "category" => "New Testament"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 22, "category" => "Gospels & Acts"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 22, "category" => "Epistles"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 22, "category" => "Revelation (Apocalypse)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 22, "category" => "Apocrypha, pseudepigrapha, & intertestamental works"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 23, "category" => "God"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 23, "category" => "Jesus Christ & his family"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 23, "category" => "Humankind"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 23, "category" => "Salvation & grace"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 23, "category" => "Spiritual beings"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 23, "category" => "Eschatology"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 23, "category" => "No longer used—formerly Future state"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 23, "category" => "Creeds, confessions of faith, covenants, & catechisms"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 23, "category" => "Apologetics & polemics"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 24, "category" => "Christian ethics"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 24, "category" => "Devotional literature"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 24, "category" => "Evangelistic writings for individuals and families"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 24, "category" => "No longer used—formerly Religious fiction"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 24, "category" => "No longer used—formerly Hymnology"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 24, "category" => "Use of art in Christianity"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 24, "category" => "Church furnishings & related articles"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 24, "category" => "Christian experience, practice, life"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 24, "category" => "Christian observances in family life"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 25, "category" => "Preaching (Homiletics)"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 25, "category" => "Texts of sermons"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 25, "category" => "Pastoral office and work (Pastoral theology)"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 25, "category" => "Parish administration"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 25, "category" => "Religious congregations & orders"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 25, "category" => "No longer used—formerly Religious societies"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 25, "category" => "No longer used—formerly Parochial schools, libraries, etc."]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 25, "category" => "No longer used—formerly Parochial medicine"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 25, "category" => "Pastoral care of families, of specific groups of people"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 26, "category" => "Social theology and interreligious relations and attitudes"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 26, "category" => "Ecclesiology"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 26, "category" => "Days, times, places of religious observance"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 26, "category" => "Public worship"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 26, "category" => "Sacraments, other rites & acts"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 26, "category" => "Missions"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 26, "category" => "Associations for religious work"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 26, "category" => "Religious education"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 26, "category" => "Spiritual renewal"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 27, "category" => "Religious congregations and orders in church history"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 27, "category" => "Persecutions in church history"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 27, "category" => "Doctrinal controversies and heresies in general church history"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 27, "category" => "Christianity in Europe"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 27, "category" => "Christianity in Asia"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 27, "category" => "Christianity in Africa"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 27, "category" => "Christianity in North America"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 27, "category" => "Christianity in South America"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 27, "category" => "History of Christianity in other areas"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 28, "category" => "Early church & Eastern churches"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 28, "category" => "Roman Catholic Church"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 28, "category" => "Anglican churches"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 28, "category" => "Protestant denominations of Continental origin & related body"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 28, "category" => "Presbyterian churches, Reformed churches centered in America, Congregational churches"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 28, "category" => "Baptist, Restoration Movement, Adventist churches"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 28, "category" => "Methodist churches; churches related to Methodism"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 28, "category" => "No longer used—formerly Unitarian"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 28, "category" => "Other denominations & sects"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 29, "category" => "No longer used—formerly Comparative religion"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 29, "category" => "Classical religion (Greek & Roman religion)"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 29, "category" => "Germanic religion"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 29, "category" => "Religions of Indic origin"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 29, "category" => "Zoroastrianism (Mazdaism, Parseeism)"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 29, "category" => "Judaism"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 29, "category" => "Islam, Bábism & Bahá'í Faith"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 29, "category" => "No longer used—formerly Mormonism"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 29, "category" => "Religions not provided for elsewhere"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 30, "category" => "Sociology & anthropology"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 30, "category" => "Social interaction"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 30, "category" => "Social processes"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 30, "category" => "Factors affecting social behavior"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 30, "category" => "Groups of people"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 30, "category" => "Culture & institutions"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 30, "category" => "Communities"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 30, "category" => "No longer used—formerly Polygraphy"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 30, "category" => "No longer used—formerly History of sociology"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 31, "category" => "No longer used—formerly Theory and methods"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 31, "category" => "No longer used—formerly Population"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 31, "category" => "No longer used—formerly Special topics"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 31, "category" => "General statistics of Europe"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 31, "category" => "General statistics of Asia"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 31, "category" => "General statistics of Africa"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 31, "category" => "General statistics of North America"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 31, "category" => "General statistics of South America"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 31, "category" => "General statistics of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 32, "category" => "Systems of governments & states"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 32, "category" => "Relation of state to organized groups & their members"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 32, "category" => "Civil & political rights"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 32, "category" => "The political process"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 32, "category" => "International migration & colonization"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 32, "category" => "Slavery & emancipation"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 32, "category" => "International relations"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 32, "category" => "The legislative process"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 32, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 33, "category" => "Labor economics"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 33, "category" => "Financial economics"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 33, "category" => "Economics of land & energy"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 33, "category" => "Cooperatives"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 33, "category" => "Socialism & related systems"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 33, "category" => "Public finance"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 33, "category" => "International economics"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 33, "category" => "Production"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 33, "category" => "Macroeconomics & related topics"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 34, "category" => "Law of nations"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 34, "category" => "Constitutional & administrative law"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 34, "category" => "Military, defense, public property, public finance, tax, commerce (trade), industrial law"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 34, "category" => "Labor, social service, education, cultural law"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 34, "category" => "Criminal law"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 34, "category" => "Private law"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 34, "category" => "Procedure & courts"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 34, "category" => "Laws, regulations, cases"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 34, "category" => "Law of specific jurisdictions, areas, socioeconomic regions, regional intergovernmental organizations"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 35, "category" => "Public administration"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 35, "category" => "General considerations of public administration"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 35, "category" => "Specific fields of public administration"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 35, "category" => "Public administration of economy & environment"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 35, "category" => "Military science"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 35, "category" => "Foot forces & warfare"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 35, "category" => "Mounted forces & warfare"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 35, "category" => "Air & other specialized forces & warfare; engineering & related services"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 35, "category" => "Sea forces & warfare"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 36, "category" => "Social problems & services"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 36, "category" => "Social problems of & services to groups of people"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 36, "category" => "Other social problems & services"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 36, "category" => "Criminology"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 36, "category" => "Penal & related institutions"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 36, "category" => "Secret associations & societies"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 36, "category" => "General clubs"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 36, "category" => "Insurance"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 36, "category" => "Associations"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 37, "category" => "Schools & their activities; special education"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 37, "category" => "Primary education (elementary education)"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 37, "category" => "Secondary education"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 37, "category" => "Adult education"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 37, "category" => "Curricula"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 37, "category" => "No longer used—formerly Education of women"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 37, "category" => "No longer used—formerly Ethical education"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 37, "category" => "Higher education (Tertiary education)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 37, "category" => "Public policy issues in education"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 38, "category" => "Commerce (Trade)"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 38, "category" => "International commerce (Foreign trade)"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 38, "category" => "Postal communication"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 38, "category" => "Communications"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 38, "category" => "Railroad transportation"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 38, "category" => "Inland waterway & ferry transportation"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 38, "category" => "Water, air, space transportation"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 38, "category" => "Transportation"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 38, "category" => "Metrology & standardization"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 39, "category" => "Costume & personal appearance"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 39, "category" => "Customs of life cycle & domestic life"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 39, "category" => "Death customs"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 39, "category" => "General customs"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 39, "category" => "Etiquette (Manners)"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 39, "category" => "No longer used—formerly Women's position and treatment"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 39, "category" => "No longer used—formerly outcast studies"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 39, "category" => "Folklore"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 39, "category" => "Customs of war & diplomacy"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 40, "category" => "Philosophy & theory; international languages"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 40, "category" => "Miscellany"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 40, "category" => "Dictionaries, encyclopedias, concordances"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 40, "category" => "Special topics of language"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 40, "category" => "Serial publications"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 40, "category" => "Organizations & management"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 40, "category" => "Education, research, related topics"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 40, "category" => "Groups of people"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 40, "category" => "Geographic treatment & biography"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 41, "category" => "Writing systems of standard forms of languages"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 41, "category" => "Etymology of standard forms of languages"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 41, "category" => "Dictionaries of standard forms of languages"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 41, "category" => "Phonology & phonetics of standard forms of languages"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 41, "category" => "Grammar of standard forms of languages"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 41, "category" => "No longer used—formerly Prosody"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 41, "category" => "Dialectology & historical linguistics"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 41, "category" => "Standard usage (Prescriptive linguistics)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 41, "category" => "Sign languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 42, "category" => "Writing system, phonology, phonetics of standard English"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 42, "category" => "Etymology of standard English"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 42, "category" => "Dictionaries of standard English"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 42, "category" => "No longer used—formerly English thesauruses"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 42, "category" => "Grammar of standard English"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 42, "category" => "No longer used—formerly English prosodies"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 42, "category" => "Historical & geographical variations, modern nongeographic variations of English"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 42, "category" => "Standard English usage (Prescriptive linguistics)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 42, "category" => "Old English (Anglo-Saxon)"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 43, "category" => "Writing systems, phonology, phonetics of standard German"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 43, "category" => "Etymology of standard German"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 43, "category" => "Dictionaries of standard German"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 43, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 43, "category" => "Grammar of standard German"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 43, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 43, "category" => "Historical & geographic variations, modern nongeographic variations of German"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 43, "category" => "Standard German usage (Prescriptive linguistics)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 43, "category" => "Other Germanic languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 44, "category" => "Writing systems, phonology, phonetics of standard French"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 44, "category" => "Etymology of standard French"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 44, "category" => "Dictionaries of standard French"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 44, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 44, "category" => "Grammar of standard French"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 44, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 44, "category" => "Historical and geographic variations, modern nongeographic variations of French"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 44, "category" => "Standard French usage (Prescriptive linguistics)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 44, "category" => "Occitan Catalan, Franco-Provençal"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 45, "category" => "Writing systems, phonology, phonetics of standard Italian"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 45, "category" => "Etymology of standard Italian"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 45, "category" => "Dictionaries of standard Italian"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 45, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 45, "category" => "Grammar of standard Italian"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 45, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 45, "category" => "Historical & geographic variations, modern nongeographic variations of Italian"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 45, "category" => "Standard Italian usage (Prescriptive linguistics)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 45, "category" => "Romanian, Rhaetian, Sardinian, Corsican"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 46, "category" => "Writing systems, phonology, phonetics of standard Spanish"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 46, "category" => "Etymology of standard Spanish"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 46, "category" => "Dictionaries of standard Spanish"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 46, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 46, "category" => "Grammar of standard Spanish"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 46, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 46, "category" => "Historical & geographic variations, modern nongeographic variations of Spanish"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 46, "category" => "Standard Spanish usage (Prescriptive linguistics)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 46, "category" => "Portuguese"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 47, "category" => "Writing systems, phonology, phonetics of classical Latin"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 47, "category" => "Etymology of classical Latin"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 47, "category" => "Dictionaries of classical Latin"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 47, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 47, "category" => "Grammar of classical Latin"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 47, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 47, "category" => "Old, postclassical, Vulgar Latin"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 47, "category" => "Classical Latin usage (Prescriptive linguistics)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 47, "category" => "Other Italic languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 48, "category" => "Writing systems, phonology, phonetics of classical Greek"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 48, "category" => "Etymology of classical Greek"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 48, "category" => "Dictionaries of classical Greek"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 48, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 48, "category" => "Grammar of classical Greek"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 48, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 48, "category" => "Preclassical & postclassical Greek"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 48, "category" => "Classical Greek usage (Prescriptive linguistics)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 48, "category" => "Other Hellenic languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 49, "category" => "East Indo-European & Celtic languages"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 49, "category" => "Afro-Asiatic languages"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 49, "category" => "Non-Semitic Afro-Asiatic languages"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 49, "category" => "Altic, Uralic, Hyperborean, Dravidian languages, miscellaneous languages of south Asia"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 49, "category" => "Languages of East & Southeast Asia"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 49, "category" => "African languages"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 49, "category" => "North American native languages"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 49, "category" => "South American native languages"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 49, "category" => "Non-Austronesian languages of Oceania, Austronesian languages, miscellaneous languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 50, "category" => "Philosophy & theory"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 50, "category" => "Miscellany"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 50, "category" => "Dictionaries, encyclopedias, concordances"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 50, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 50, "category" => "Serial publications"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 50, "category" => "Organizations & management"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 50, "category" => "Education, research, related topics"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 50, "category" => "Natural history"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 50, "category" => "History, geographic treatment, biography"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 51, "category" => "General principles of mathematics"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 51, "category" => "Algebra"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 51, "category" => "Arithmetic"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 51, "category" => "Topology"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 51, "category" => "Analysis"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 51, "category" => "Geometry"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 51, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 51, "category" => "Numerical analysis"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 51, "category" => "Probabilities & applied mathematics"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 52, "category" => "Celestial mechanics"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 52, "category" => "Techniques, procedures, apparatus, equipment, materials"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 52, "category" => "Specific celestial bodies & phenomena"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 52, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 52, "category" => "Earth (Astronomical geography)"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 52, "category" => "Mathematical geography"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 52, "category" => "Celestial navigation"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 52, "category" => "Ephemerides"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 52, "category" => "Chronology"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 53, "category" => "Classical mechanics"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 53, "category" => "Fluid mechanics"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 53, "category" => "Pneumatics (Gas mechanics)"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 53, "category" => "Sound & related vibrations"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 53, "category" => "Light & related radiation"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 53, "category" => "Heat"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 53, "category" => "Electricity & electronics"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 53, "category" => "Magnetism"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 53, "category" => "Modern physics"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 54, "category" => "Physical chemistry"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 54, "category" => "Techniques, procedures, apparatus, equipment, materials"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 54, "category" => "Analytical chemistry"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 54, "category" => "No longer used—formerly Qualitative analysis"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 54, "category" => "No longer used—formerly Quantitative analysis"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 54, "category" => "Inorganic chemistry"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 54, "category" => "Organic chemistry"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 54, "category" => "Crystallography"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 54, "category" => "Mineralogy"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 55, "category" => "Geology, hydrology, meteorology"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 55, "category" => "Petrology"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 55, "category" => "Economic geology"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 55, "category" => "Earth sciences of Europe"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 55, "category" => "Earth sciences of Asia"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 55, "category" => "Earth sciences of Africa"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 55, "category" => "Earth sciences of North America"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 55, "category" => "Earth sciences of South America"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 55, "category" => "Earth sciences of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, extraterrestrial worlds"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 56, "category" => "Paleobotany; fossil microorganisms"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 56, "category" => "Fossil invertebrates"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 56, "category" => "Miscellaneous fossil marine & seashore invertebrates"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 56, "category" => "Fossil Mollusca & Molluscoidea"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 56, "category" => "Fossil Arthropoda"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 56, "category" => "Fossil Chordata"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 56, "category" => "Fossil cold-blooded vertebrates"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 56, "category" => "Fossil Aves (birds)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 56, "category" => "Fossil Mammalia"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 57, "category" => "Physiology & related subjects"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 57, "category" => "Biochemistry"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 57, "category" => "Specific physiological systems in animals, regional histology & physiology in animals"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 57, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 57, "category" => "Specific parts of & physiological systems in plants"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 57, "category" => "Genetics and evolution"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 57, "category" => "Ecology"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 57, "category" => "Natural history of organisms & related subjects"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 57, "category" => "Natural history of microorganisms, fungi, algae"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 58, "category" => "Specific topics in natural history of plants"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 58, "category" => "Plants noted for specific vegetative characteristics and flowers"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 58, "category" => "Magnoliopsida (Dicotyledones)"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 58, "category" => "Liliopsida (Monocotyledones)"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 58, "category" => "Pinophyta (Gymnosperms)"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 58, "category" => "Cryptogamia (Seedless plants)"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 58, "category" => "Pteridophyta"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 58, "category" => "Bryophyta"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 58, "category" => "No longer used—formerly Forestry"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 59, "category" => "Specific topics in natural history of animals"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 59, "category" => "Invertebrates"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 59, "category" => "Miscellaneous marine & seashore invertebrates"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 59, "category" => "Mollusca & Molluscoidea"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 59, "category" => "Arthropoda"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 59, "category" => "Chordata"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 59, "category" => "Cold-blooded vertebrates"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 59, "category" => "Aves (Birds)"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 59, "category" => "Mammalia (Mammals)"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 60, "category" => "Philosophy & theory"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 60, "category" => "Miscellany"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 60, "category" => "Dictionaries, encyclopedias, concordances"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 60, "category" => "Technical drawing, hazardous materials technology; groups of people"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 60, "category" => "Serial publications"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 60, "category" => "Organizations"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 60, "category" => "Education, research, related topics"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 60, "category" => "Patents"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 60, "category" => "History, geographic treatment, biography"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 61, "category" => "Human anatomy, cytology, histology"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 61, "category" => "Respiratory (lung, respiratory system)"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 61, "category" => "Gastrointestinal (dental anatomy)"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 61, "category" => "Genitourinary (genital system)"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 61, "category" => "Musculoskeletal (seed coat)"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 61, "category" => "Anatomy of the sense organs and nervous system"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 61, "category" => "Anatomy of the brain"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 61, "category" => "Topographic anatomy (back)"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 61, "category" => "Human physiology"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Personal health & safety"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Professions hygiene and health"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Role of the natural environment"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Diet (food hygiene, nutrition, diet, nutritional value of food and beverages)"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Cleanliness Care (hygiene and personal cleanliness, personal care)"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Role of unnatural environment (housing, housing, temperature)"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => ""]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Hygiene in the business (industrial hygiene)"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Self Defense"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Condition physique (bodybuilding, fitness, forme physique)[4]"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Hatha yoga, yoga physique[5]"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Exercising, sports (aerobics, sauna, appearance surveillance and physical form)[6]"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 61, "category" => "Relaxation, sleep[7]"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 61, "category" => "Forensic medicine; incidence of injuries, wounds, disease; public preventive medicine"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 61, "category" => "Pharmacology and therapeutics"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 61, "category" => "Diseases"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 61, "category" => "Surgery, regional medicine, dentistry, ophthalmology, otology, audiology"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 61, "category" => "Gynecology, obstetrics, pediatrics, geriatrics"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 61, "category" => "No longer used—formerly Experimental medicine"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 62, "category" => "Applied physics"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 62, "category" => "Mining & related operations"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 62, "category" => "Military & nautical engineering"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 62, "category" => "Civil engineering"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 62, "category" => "Engineering of railroads, roads"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 62, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 62, "category" => "Hydraulic engineering"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 62, "category" => "Sanitary engineering"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 62, "category" => "Other branches of engineering"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 63, "category" => "Specific techniques; apparatus, equipment, materials"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 63, "category" => "Plant injuries, diseases, pests"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 63, "category" => "Field & plantation crops"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 63, "category" => "Orchards, fruits, forestry"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 63, "category" => "Garden crops (Horticulture)"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 63, "category" => "Animal husbandry"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 63, "category" => "Processing dairy & related products"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 63, "category" => "Insect culture"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 63, "category" => "Hunting, fishing, conservation, related technologies"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 64, "category" => "Food & drink"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 64, "category" => "Meals & table service"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 64, "category" => "Housing & household equipment"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 64, "category" => "Household utilities"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 64, "category" => "Household furnishings"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 64, "category" => "Sewing, clothing, management of personal and family life"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 64, "category" => "Management of public households (Institutional housekeeping)"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 64, "category" => "Housekeeping"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 64, "category" => "Child rearing; home care of people with disabilities & illnesses"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 65, "category" => "Office services"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 65, "category" => "Processes of written communication"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 65, "category" => "Shorthand"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 65, "category" => "Accounting"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 65, "category" => "General management"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 65, "category" => "Advertising & public relations"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 66, "category" => "Technology of industrial chemicals"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 66, "category" => "Technology of explosives, fuels, related products"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 66, "category" => "Beverage technology"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 66, "category" => "Food technology"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 66, "category" => "Technology of industrial oils, fats, waxes, gases"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 66, "category" => "Ceramic & allied technologies"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 66, "category" => "Cleaning, color, coating, related technologies"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 66, "category" => "Technology of other organic products"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 66, "category" => "Metallurgy"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 67, "category" => "Metalworking processes & primary metal products"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 67, "category" => "Iron, steel, other iron alloys"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 67, "category" => "Nonferrous metals"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 67, "category" => "Lumber processing, wood products, cork"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 67, "category" => "Leather & fur processing"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 67, "category" => "Pulp & paper technology"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 67, "category" => "Textiles"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 67, "category" => "Elastomers & elastomer products"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 67, "category" => "Other products of specific kinds of materials"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 68, "category" => "Precision instruments[disambiguation needed] & other devices"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 68, "category" => "Small forge work (Blacksmithing)"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 68, "category" => "Hardware & household appliances"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 68, "category" => "Furnishings & home workshops"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 68, "category" => "Leather & fur goods, & related products"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 68, "category" => "Printing & related activities"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 68, "category" => "Clothing & accessories"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 68, "category" => "Other final products, & packaging technology"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 68, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 69, "category" => "Building materials"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 69, "category" => "Auxiliary construction practices"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 69, "category" => "Construction in specific types of materials & for specific purposes"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 69, "category" => "Wood construction"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 69, "category" => "Roof covering"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 69, "category" => "Utilities"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 69, "category" => "Heating, ventilating, air-conditioning engineering"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 69, "category" => "Detail finishing"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 69, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 70, "category" => "Philosophy & theory of fine & decorative arts"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 70, "category" => "Miscellany of fine & decorative arts"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 70, "category" => "Dictionaries, encyclopedias, concordances of fine & decorative arts"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 70, "category" => "Special topics in fine & decorative arts"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 70, "category" => "Serial publications of fine & decorative arts"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 70, "category" => "Organizations & management of fine & decorative arts"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 70, "category" => "Education, research, related topics of fine & decorative arts"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 70, "category" => "Galleries, museums, private collections of fine & decorative arts"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 70, "category" => "History, geographic treatment, biography"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 71, "category" => "Area planning (Civic art)"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 71, "category" => "Landscape architecture (Landscape design)"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 71, "category" => "Landscape architecture of trafficways"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 71, "category" => "Water features in landscape architecture"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 71, "category" => "Woody plants in landscape architecture"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 71, "category" => "Herbaceous plants in landscape architecture"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 71, "category" => "Structures in landscape architecture"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 71, "category" => "Landscape design of cemeteries"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 71, "category" => "Natural landscapes"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 72, "category" => "Architectural materials & structural elements"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 72, "category" => "Architecture from earliest times to ca. 300"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 72, "category" => "Architecture from ca. 300 to 1399"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 72, "category" => "Architecture from 1400"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 72, "category" => "Public structures"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 72, "category" => "Buildings for religious & related purposes"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 72, "category" => "Buildings for educational & research purposes"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 72, "category" => "Residential & related buildings"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 72, "category" => "Design & decoration of structures & accessories"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 73, "category" => "Processes, forms, subjects of sculpture"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 73, "category" => "Sculpture from earliest times to ca. 500, sculpture of non-literate peoples"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 73, "category" => "Greek, Etruscan, Roman sculpture"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 73, "category" => "Sculpture from ca. 500 to 1399"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 73, "category" => "Sculpture from 1400"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 73, "category" => "Carving & carvings"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 73, "category" => "Numismatics & sigillography"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 73, "category" => "Ceramic arts"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 73, "category" => "Art metalwork"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 74, "category" => "Drawing & drawings"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 74, "category" => "Perspective in drawing"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 74, "category" => "Drawing & drawings by subject"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 74, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 74, "category" => "Decorative arts"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 74, "category" => "Textile arts"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 74, "category" => "Interior decoration"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 74, "category" => "Glass"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 74, "category" => "Furniture & accessories"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 75, "category" => "Techniques, procedures, apparatus, equipment, materials, forms"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 75, "category" => "Color"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 75, "category" => "Symbolism, allegory, mythology, legend"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 75, "category" => "Genre paintings"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 75, "category" => "Religion"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 75, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 75, "category" => "Human figures"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 75, "category" => "Nature, architectural subjects & cityscapes, other specific subjects"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 75, "category" => "History, geographic treatment, biography"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 76, "category" => "Relief processes (Block printing)"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 76, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 76, "category" => "Lithographic processes (Planographic processes)"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 76, "category" => "Chromolithography & serigraphy"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 76, "category" => "Metal engraving"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 76, "category" => "Mezzotinting, aquatinting, & related processes"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 76, "category" => "Etching & drypoint"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 76, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 76, "category" => "Prints"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 77, "category" => "Techniques, procedures, apparatus, equipment, materials"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 77, "category" => "Metallic salt processes"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 77, "category" => "Pigment processes of printing"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 77, "category" => "No longer used—formerly Holography"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 77, "category" => "No longer used—formerly Digital photography"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 77, "category" => "Computer art (Digital art)"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 77, "category" => "Cinematography & Videography"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 77, "category" => "Specific fields & special kinds of photography"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 77, "category" => "Photographic images"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 78, "category" => "General principles & musical forms"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 78, "category" => "Vocal music"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 78, "category" => "Music for single voices"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 78, "category" => "Instruments & Instrumental ensembles & their music"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 78, "category" => "Ensembles with only one instrument per part"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 78, "category" => "Keyboard, mechanical, electrophonic, percussion instruments"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 78, "category" => "Stringed instruments (Chordophones)"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 78, "category" => "Wind instruments (Aerophones)"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 79, "category" => "Public performances"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 79, "category" => "Stage presentations"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 79, "category" => "Indoor games & amusements"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 79, "category" => "Indoor games of skill"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 79, "category" => "Games of chance"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 79, "category" => "Athletic & outdoor sports & games"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 79, "category" => "Aquatic & air sports"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 79, "category" => "Equestrian sports & animal racing"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 79, "category" => "Fishing, hunting, shooting"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 80, "category" => "Philosophy & theory"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 80, "category" => "Miscellany"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 80, "category" => "Dictionaries, encyclopedias, concordances"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 80, "category" => "Not assigned or no longer used"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 80, "category" => "Serial publications"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 80, "category" => "Organizations & management"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 80, "category" => "Education, research, related topics"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 80, "category" => "Rhetoric & collections of literary texts from more than two literatures"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 80, "category" => "History, description, critical appraisal of more than two literatures"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 81, "category" => "American poetry in English"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 81, "category" => "American drama in English"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 81, "category" => "American fiction in English"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 81, "category" => "American essays in English"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 81, "category" => "American speeches in English"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 81, "category" => "American letters in English"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 81, "category" => "American humor & satire in English"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 81, "category" => "American miscellaneous writings in English"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 81, "category" => "No longer used—formerly Puzzle activities"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 82, "category" => "English Poetry"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 82, "category" => "English drama"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 82, "category" => "William Shakespeare"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 82, "category" => "English fiction"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 82, "category" => "English essays"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 82, "category" => "English speeches"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 82, "category" => "English letters"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 82, "category" => "English humor & satire"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 82, "category" => "English miscellaneous writings"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 82, "category" => "Old English (Anglo-Saxon) literature"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 83, "category" => "German poetry"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 83, "category" => "German drama"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 83, "category" => "German fiction"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 83, "category" => "German essays"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 83, "category" => "German speeches"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 83, "category" => "German letters"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 83, "category" => "German humor & satire"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 83, "category" => "German miscellaneous writings"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 83, "category" => "Other Germanic literatures"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 84, "category" => "French poetry"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 84, "category" => "French drama"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 84, "category" => "French fiction"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 84, "category" => "French essays"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 84, "category" => "French speeches"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 84, "category" => "French letters"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 84, "category" => "French humor & satire"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 84, "category" => "French miscellaneous writings"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 84, "category" => "Occitan, Catalan, Franco-Provençal literatures"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 85, "category" => "Italian poetry"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 85, "category" => "Italian drama"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 85, "category" => "Italian fiction"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 85, "category" => "Italian essays"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 85, "category" => "Italian speeches"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 85, "category" => "Italian letters"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 85, "category" => "Italian humor & satire"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 85, "category" => "Italian miscellaneous writings"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 85, "category" => "Literatures of Romanian, Rhaetian, Sardinian, Corsican languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 86, "category" => "Spanish poetry"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 86, "category" => "Spanish drama"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 86, "category" => "Spanish fiction"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 86, "category" => "Spanish essays"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 86, "category" => "Spanish speeches"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 86, "category" => "Spanish letters"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 86, "category" => "Spanish humor & satire"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 86, "category" => "Spanish miscellaneous writings"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 86, "category" => "Literatures of Portuguese & Galician languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 87, "category" => "Latin poetry"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 87, "category" => "Latin dramatic poetry & drama"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 87, "category" => "Latin epic poetry & fiction"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 87, "category" => "Latin lyric poetry"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 87, "category" => "Latin speeches"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 87, "category" => "Latin letters"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 87, "category" => "Latin humor & satire"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 87, "category" => "Latin miscellaneous writings"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 87, "category" => "Literatures of other Italic languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 88, "category" => "Classical Greek poetry"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 88, "category" => "Classical Greek drama"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 88, "category" => "Classical Greek epic poetry & fiction"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 88, "category" => "Classical Greek lyric poetry"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 88, "category" => "Classical Greek speeches"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 88, "category" => "Classical Greek letters"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 88, "category" => "Classical Greek humor & satire"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 88, "category" => "Classical Greek miscellaneous writings"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 88, "category" => "Modern Greek literature"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 89, "category" => "East Indo-European & Celtic literatures"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 89, "category" => "Afro-Asiatic literatures"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 89, "category" => "Non-Semitic Afro-Asiatic literatures"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 89, "category" => "Literatures of Altaic, Uralic, Hyperborean, Dravidian languages; literatures of miscellaneous languages of South Asia"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 89, "category" => "Literatures of East & Southeast Asia"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 89, "category" => "African literatures"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 89, "category" => "Literatures of North American native languages"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 89, "category" => "Literatures of South American native languages"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 89, "category" => "Literatures of non-Austronesian languages of Oceania, of Austronesian languages, of miscellaneous languages"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 90, "category" => "Philosophy & theory of history"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 90, "category" => "Miscellany of history"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 90, "category" => "Dictionaries, encyclopedias, concordances of history"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 90, "category" => "Collected accounts of events"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 90, "category" => "Serial publications of history"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 90, "category" => "Organizations & management of history"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 90, "category" => "Education, research, related topics of history"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 90, "category" => "History with respect to groups of people"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 90, "category" => "World history"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 91, "category" => "Historical geography"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 91, "category" => "Graphic representations of surface of earth and of extraterrestrial worlds"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 91, "category" => "Geography of & travel in ancient world"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 91, "category" => "Geography of & travel in Europe"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 91, "category" => "Geography of & travel in Asia"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 91, "category" => "Geography of & travel in Africa"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 91, "category" => "Geography of & travel in North America"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 91, "category" => "Geography of & travel in South America"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 91, "category" => "Geography of & travel in Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, & on extraterrestrial worlds"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 2, "category" => "Genealogy, names, insignia"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 93, "category" => "China to 420"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 93, "category" => "Egypt to 640"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 93, "category" => "Palestine to 70"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 93, "category" => "South Asia to 647"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 93, "category" => "Mesopotamia to 637 & Iranian Plateau to 637"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 93, "category" => "Europe north & west of Italian Peninsula to ca. 499"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 93, "category" => "Italian Peninsula to 476 & adjacent territories to 476"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 93, "category" => "Greece to 323"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 93, "category" => "Other parts of ancient world"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 94, "category" => "British Isles"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 94, "category" => "England & Wales"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 94, "category" => "Germany & neighboring central European countries"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 94, "category" => "France & Monaco"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 94, "category" => "Italy, San Marino, Vatican City, Malta"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 94, "category" => "Spain, Andorra, Gibraltar, Portugal"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 94, "category" => "Russia & neighboring east European countries"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 94, "category" => "Scandinavia"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 94, "category" => "Other parts of Europe"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 95, "category" => "China & adjacent areas"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 95, "category" => "Japan"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 95, "category" => "Arabian Peninsula & adjacent areas"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 95, "category" => "India & neighboring south Asian countries;"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 95, "category" => "Iran"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 95, "category" => "Middle East (Near East)"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 95, "category" => "Siberia (Asiatic Russia)"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 95, "category" => "Central Asia"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 95, "category" => "Southeast Asia"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 96, "category" => "Tunisia & Libya"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 96, "category" => "Egypt, Sudan, South Sudan"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 96, "category" => "Ethiopia & Eritrea"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 96, "category" => "Morocco, Ceuta, Melilla Western Sahara, Canary Islands"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 96, "category" => "Algeria"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 96, "category" => "West Africa & offshore islands"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 96, "category" => "Central Africa & offshore islands"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 96, "category" => "Republic of South Africa & neighboring southern African countries"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 96, "category" => "South Indian Ocean islands"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 97, "category" => "Canada"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 97, "category" => "Mexico, Central America, West Indies, Bermuda"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 97, "category" => "United States"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 97, "category" => "Northeastern United States (New England & Middle Atlantic states)"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 97, "category" => "Southeastern United States (South Atlantic states)"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 97, "category" => "South central United States"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 97, "category" => "North central United States"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 97, "category" => "Western United States"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 97, "category" => "Great Basin & Pacific Slope region of United States"]);
		DB::table("deweys")->insert(["number" => 1,"parent" => 98, "category" => "Brazil"]);
		DB::table("deweys")->insert(["number" => 2,"parent" => 98, "category" => "Argentina"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 98, "category" => "Chile"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 98, "category" => "Bolivia"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 98, "category" => "Peru"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 98, "category" => "Colombia & Ecuador"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 98, "category" => "Venezuela"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 98, "category" => "Guiana"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 98, "category" => "Paraguay & Uruguay"]);
		DB::table("deweys")->insert(["number" => 3,"parent" => 99, "category" => "New Zealand"]);
		DB::table("deweys")->insert(["number" => 4,"parent" => 99, "category" => "Australia"]);
		DB::table("deweys")->insert(["number" => 5,"parent" => 99, "category" => "New Guinea & neighboring countries of Melanesia"]);
		DB::table("deweys")->insert(["number" => 6,"parent" => 99, "category" => "Polynesia & other Pacific Ocean islands"]);
		DB::table("deweys")->insert(["number" => 7,"parent" => 99, "category" => "Atlantic Ocean islands"]);
		DB::table("deweys")->insert(["number" => 8,"parent" => 99, "category" => "Arctic islands & Antarctica"]);
		DB::table("deweys")->insert(["number" => 9,"parent" => 99, "category" => "Extraterrestrial worlds"]);
	}
}
